// THIS CODE IS A PLACE HOLDER AND WILL BE REPLACED BY GO GENERATE
// ! DO NOT EDIT THIS FILE OR COMMIT THIS FILE TO THE REPOSITORY !

package zobrist

import (
	"laptudirm.com/x/mess/pkg/chess/square"
	"laptudirm.com/x/mess/pkg/chess/move/castling"
	"laptudirm.com/x/mess/pkg/chess/piece"
)

// placeholder declarations with docs

// PieceSquare contains zobrist keys for each type of piece on every
// square. It can be index by PieceSquare[pieceType][pieceSquare].
var PieceSquare[piece.NType][square.N]Key

// EnPassant contains the zobrist keys for all possible en passant
// capture squares on each file. It can be indexed by EnPassant[file].
var EnPassant [square.FileN]Key

// Castling contains zobrist keys for every possible permutation of
// castling rights. It can be indexed by Castling[castlingRights].
var Castling [castling.N]Key

// SideToMove represents the zobrist key for when the side to move is
// black. There is no zobrist key for when the side to move is white.
var SideToMove Key
