// THIS CODE IS A PLACE HOLDER AND WILL BE REPLACED BY GO GENERATE
// ! DO NOT EDIT THIS FILE OR COMMIT THIS FILE TO THE REPOSITORY !

package attacks

import (
	"laptudirm.com/x/mess/pkg/chess/square"
	"laptudirm.com/x/mess/pkg/chess/bitboard"
	"laptudirm.com/x/mess/pkg/chess/move/attacks/magic"
	"laptudirm.com/x/mess/pkg/chess/piece"
)

// King contains all the attack sets of a king indexed by it's square.
var King   [square.N]bitboard.Board

// Knight contains all the attack sets of a knight indexed by it's square.
var Knight [square.N]bitboard.Board

// Pawn contains all the attack sets of a pawn indexed by it's color and 
// square. Note these are the diagonal attack sets, not move sets.
var Pawn   [piece.NColor][square.N]bitboard.Board

// magic tables for sliding pieces

var rookTable   magic.Table
var bishopTable magic.Table
