// THIS CODE IS A PLACE HOLDER AND WILL BE REPLACED BY GO GENERATE
// ! DO NOT EDIT THIS FILE OR COMMIT THIS FILE TO THE REPOSITORY !

package bitboard

import "laptudirm.com/x/mess/pkg/chess/square"

// Between contains bitboards which have the path between two squares set.
// The definition of path is only valid for squares which lie on the same
// file, rank, diagonal, or anti-diagonal. For all other square
// combinations, the path is Empty.
var Between [square.N][square.N]Board

// Squares contains bitboards for each square where only that square's bit
// is set. Squares[square] is equivalent to Board(1 << square).
var Squares [square.N]Board
